version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      astro-ecosystem:
        patterns:
          - 'astro'
          - '@astrojs/*'
        update-types:
          - 'minor'
          - 'patch'
      lint-and-format:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - 'prettier*'
        update-types:
          - 'minor'
          - 'patch'
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - 'astro'
          - '@astrojs/*'
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - 'prettier*'
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'github-actions'
